#!/bin/bash
#
# greens
#
# Mirrors commit timestamps from private work repos to a public repo,
# making your contribution graph reflect actual work without exposing code.
#
# https://github.com/yuvrajangadsingh/greens

set -euo pipefail

# Resolve symlinks when locating ourselves. The curl|bash installer symlinks
# /usr/local/bin/greens -> ~/.contrib-mirror/src/sync.sh; without this loop
# SCRIPT_DIR points at the bin dir and setup.sh is never found.
SCRIPT_SOURCE="${BASH_SOURCE[0]}"
while [[ -L "$SCRIPT_SOURCE" ]]; do
  _link_target="$(readlink "$SCRIPT_SOURCE")"
  case "$_link_target" in
    /*) SCRIPT_SOURCE="$_link_target" ;;
    *)  SCRIPT_SOURCE="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)/$_link_target" ;;
  esac
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_SOURCE")" && pwd)"
VERSION="1.8.2"

# Config file location. Config uses ${VAR:-value} so env vars take precedence.
CONFIG_FILE="${CONTRIB_MIRROR_CONFIG:-$HOME/.contrib-mirror/config}"

# ─────────────────────────────────────────────────────────────────────────────
# Config/token hygiene — BEFORE sourcing. The config can hold a PAT and is
# executed as shell, so a config owned by someone else is refused outright.
# Loose permissions are tightened with a rotate-the-PAT advisory (chmod after
# the fact is not remediation on a shared machine).
# ─────────────────────────────────────────────────────────────────────────────

if [[ -d "$HOME/.contrib-mirror" ]]; then
  chmod 700 "$HOME/.contrib-mirror" 2>/dev/null || true
fi
if [[ -f "$CONFIG_FILE" ]]; then
  if [[ ! -O "$CONFIG_FILE" ]]; then
    echo "ERROR: $CONFIG_FILE is not owned by the current user. Refusing to load it." >&2
    exit 1
  fi
  if [[ -L "$CONFIG_FILE" ]]; then
    echo "NOTE: $CONFIG_FILE is a symlink; greens won't adjust or rewrite it." >&2
  else
    _config_perms="$(stat -f '%Lp' "$CONFIG_FILE" 2>/dev/null || stat -c '%a' "$CONFIG_FILE" 2>/dev/null || echo "")"
    case "$_config_perms" in
      ""|*00) : ;;  # already owner-only (600/700/400/...) or unknown
      *)
        echo "WARN: $CONFIG_FILE was group/world-readable (mode $_config_perms); tightening to 600." >&2
        if grep -q "GITHUB_TOKEN" "$CONFIG_FILE" 2>/dev/null; then
          echo "WARN: it contains a GitHub token. chmod is not remediation on a shared machine — rotate the PAT." >&2
        fi
        chmod 600 "$CONFIG_FILE" 2>/dev/null || true
        ;;
    esac
  fi
fi

# Source config file if it exists
# shellcheck disable=SC1090
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE"

# ─────────────────────────────────────────────────────────────────────────────
# Atomic config writes. The config can hold a PAT; every write path is
# same-directory temp + chmod 600 + rename. Never append to the live file.
# ─────────────────────────────────────────────────────────────────────────────

config_upsert() {
  # $1 = key, $2 = full replacement line. Replaces the KEY=... line or appends.
  local key="$1" line="$2" tmp="${CONFIG_FILE}.tmp.$$"
  if [[ -L "$CONFIG_FILE" ]]; then
    echo "ERROR: $CONFIG_FILE is a symlink; refusing to rewrite it. Update it manually:" >&2
    echo "  $line" >&2
    return 1
  fi
  (
    umask 077
    { grep -v "^${key}=" "$CONFIG_FILE" 2>/dev/null || true
      printf '%s\n' "$line"
    } > "$tmp"
  )
  chmod 600 "$tmp" 2>/dev/null || true
  mv "$tmp" "$CONFIG_FILE"
}

# ─────────────────────────────────────────────────────────────────────────────
# Legacy generated-README detection (greens <= 1.8.1 wrote a dashboard README
# into the mirror that listed work repo NAMES). v1.8.2 removed the feature;
# --privacy-migrate rewrites history to purge it. The signature identifies OUR
# generated file with high specificity — anything else is user content, never
# touched. Both historical footers (pre- and post-rename) are recognized.
# ─────────────────────────────────────────────────────────────────────────────

is_generated_readme_content() {
  # $1 = README content. Returns 0 only for files old greens versions wrote:
  # exact heading + all three table section markers + a recognized footer or
  # the exact generator explanatory sentence (covers user-truncated copies).
  local content="$1"
  [[ "${content%%$'\n'*}" == "# Work Contributions Mirror" ]] || return 1
  case "$content" in
    *'## Overview'*) : ;;
    *) return 1 ;;
  esac
  case "$content" in
    *'## Repository Breakdown'*) : ;;
    *) return 1 ;;
  esac
  case "$content" in
    *'## Sync Info'*) : ;;
    *) return 1 ;;
  esac
  case "$content" in
    *'Generated by [greens](https://github.com/yuvrajangadsingh/greens)'*) return 0 ;;
    *'Generated by [private-work-contributions-mirror](https://github.com/yuvrajangadsingh/private-work-contributions-mirror)'*) return 0 ;;
    *'This repository mirrors commit'*'from private work repositories'*) return 0 ;;
  esac
  return 1
}

# Scan every historical root README.md blob reachable from ALL local refs of
# a repo (plus the worktree file). Echoes: none | generated | foreign
#   generated = at least one greens-generated README blob is reachable
#   foreign   = README blobs exist but none/only-some match the signature
# "generated" wins over "foreign" (mixed history still needs the migrate gate).
scan_repo_readme_state() {
  local mdir="$1" found_generated=0 found_foreign=0 c blob content
  # Historical blobs: every distinct root README.md blob was introduced by a
  # commit that changed README.md, so rev-list --all -- README.md is a
  # complete candidate prefilter; content-sniff decides ownership.
  while IFS= read -r c; do
    [[ -z "$c" ]] && continue
    blob="$(git -C "$mdir" rev-parse --verify --quiet "$c:README.md" 2>/dev/null || true)"
    [[ -z "$blob" ]] && continue
    content="$(git -C "$mdir" cat-file blob "$blob" 2>/dev/null || true)"
    if is_generated_readme_content "$content"; then
      found_generated=1
    else
      found_foreign=1
    fi
  done < <(git -C "$mdir" rev-list --all -- README.md 2>/dev/null || true)
  # Worktree copy (may be uncommitted legacy output)
  if [[ -f "$mdir/README.md" ]]; then
    content="$(cat "$mdir/README.md" 2>/dev/null || true)"
    if is_generated_readme_content "$content"; then
      found_generated=1
    else
      found_foreign=1
    fi
  fi
  if [[ "$found_generated" -eq 1 ]]; then
    echo "generated"
  elif [[ "$found_foreign" -eq 1 ]]; then
    echo "foreign"
  else
    echo "none"
  fi
}

# Per-run cached GitHub visibility of the mirror: private | public | unverifiable
# GitHub-ness is judged on BOTH the raw configured URL and the effective
# (insteadOf-applied) URL. Non-GitHub remotes are "unverifiable" — greens can
# only prove privacy for repos gh can query. One API call per run, cached.
MIRROR_VIS=""
mirror_visibility() {
  if [[ -n "$MIRROR_VIS" ]]; then
    echo "$MIRROR_VIS"
    return 0
  fi
  local raw effective src="" vis="" owner_repo=""
  raw="$(git -C "$MIRROR_DIR" config remote.origin.url 2>/dev/null || true)"
  effective="$(git -C "$MIRROR_DIR" remote get-url origin 2>/dev/null || true)"
  case "$raw" in *github*) src="$raw" ;; esac
  if [[ -z "$src" ]]; then
    case "$effective" in *github*) src="$effective" ;; esac
  fi
  MIRROR_VIS="unverifiable"
  if [[ -n "$src" ]]; then
    owner_repo="$(echo "$src" | sed -n 's|.*[:/]\([^/:]*/[^/:]*\)$|\1|p')"
    owner_repo="${owner_repo%.git}"
    if [[ -n "$owner_repo" ]] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
      vis="$(gh repo view "$owner_repo" --json visibility -q .visibility 2>/dev/null || true)"
      case "$vis" in
        PRIVATE|private) MIRROR_VIS="private" ;;
        PUBLIC|public)   MIRROR_VIS="public" ;;
      esac
    fi
  fi
  echo "$MIRROR_VIS"
}

# Refusal for dashboard-README history on a mirror that is NOT verified
# private. Deliberately has no bypass.
legacy_refuse() {
  {
    echo "ERROR: this mirror's history contains the greens dashboard README (it lists"
    echo "your work repository NAMES), and the mirror is not verified PRIVATE — it is"
    echo "public, or its visibility could not be checked. greens will not extend that"
    echo "history where others can read it."
    echo ""
    echo "Fix ONE of these, then re-run:"
    echo "  1. Make the GitHub mirror private (repo Settings > Danger Zone) and make"
    echo "     sure the GitHub CLI can verify it:  gh auth login  (personal account)."
    echo "     On a verified-private mirror the dashboard is a feature — only people"
    echo "     with access to the repo can see it."
    echo "  2. Scrub the history entirely:  greens --privacy-migrate"
    echo "     (verifies greens-managed content, writes a private local recovery"
    echo "     bundle, rewrites the default branch, force-pushes; never deletes"
    echo "     unrecognized user files)."
    echo ""
    echo "History rewrites cannot recall existing clones, forks, caches, screenshots,"
    echo "or old-SHA URLs. There is no greens bypass for this safety check."
  } >&2
  exit 3
}

# ─────────────────────────────────────────────────────────────────────────────
# greens --privacy-migrate
#
# One-shot, confirmed HISTORY REWRITE of the mirror repo. Removes the legacy
# generated README (work repo names) from every commit, drops init/status
# commits, re-authors everything as MIRROR_NAME <MIRROR_EMAIL>, redacts
# previously copied messages to "sync" (unless --keep-messages), and
# force-pushes the remote default branch. Author dates are preserved exactly,
# so the contribution graph does not change.
# ─────────────────────────────────────────────────────────────────────────────

privacy_migrate() {
  # Owner-only for everything we create (manifests, bundle, build repo).
  umask 077

  local keep_messages=0 arg
  for arg in "$@"; do
    case "$arg" in
      --keep-messages) keep_messages=1 ;;
      *) echo "Unknown option for --privacy-migrate: $arg" >&2; exit 1 ;;
    esac
  done

  echo "greens — privacy migrate"
  echo ""

  if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "  No config found ($CONFIG_FILE). Run: greens --setup"
    exit 1
  fi
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
  MIRROR_DIR="${MIRROR_DIR:-$HOME/.contrib-mirror/mirror}"
  MIRROR_NAME="${MIRROR_NAME:-greens}"
  MIRROR_EMAIL="${MIRROR_EMAIL:-}"
  MIRROR_EMAIL="${MIRROR_EMAIL//[[:space:]]/}"

  if [[ -z "$MIRROR_EMAIL" ]]; then
    echo "  ERROR: MIRROR_EMAIL is not set. The rewrite re-authors every commit"
    echo "  with your personal GitHub email. Run: greens --setup"
    exit 2
  fi

  if [[ ! -d "$MIRROR_DIR/.git" ]]; then
    echo "  No mirror repo at $MIRROR_DIR. Nothing to migrate."
    exit 1
  fi

  # Raw configured URL (NOT `remote get-url`, which applies insteadOf
  # rewrites): the configured URL is what identifies the GitHub repo for the
  # visibility check; per-operation rewrites still apply to fetch/push.
  local remote_url
  remote_url="$(git -C "$MIRROR_DIR" config remote.origin.url 2>/dev/null || true)"
  if [[ -z "$remote_url" ]]; then
    echo "  Mirror repo has no 'origin' remote. Run: greens --setup"
    exit 1
  fi
  local masked_url
  masked_url="$(echo "$remote_url" | sed 's|https://[^@]*@|https://****@|')"

  # ── Step 1: resolve the remote default branch ────────────────────────────
  local symref_out default_branch
  if ! symref_out="$(git -C "$MIRROR_DIR" ls-remote --symref origin HEAD 2>&1)"; then
    echo "  ERROR: can't reach the mirror remote ($masked_url):"
    echo "$symref_out" | tail -3 | sed 's/^/    /'
    echo "  Nothing was changed. Fix access (greens --setup) and re-run."
    exit 1
  fi
  default_branch="$(printf '%s\n' "$symref_out" | awk '/^ref:/ {sub("refs/heads/", "", $2); print $2; exit}')"

  # ── Step 2: visibility — fail CLOSED for GitHub mirrors ──────────────────
  # A typed YES is not proof the repo is private. For GitHub-hosted mirrors we
  # require gh to positively report PRIVATE before rewriting; the old history
  # keeps being served while public.
  # Detection looks at BOTH the raw configured URL and the effective URL
  # (get-url, which applies insteadOf rewrites) — either one naming GitHub
  # means the mirror lives there. Fetch/push still use the raw config.
  local effective_url gh_source_url="" github_mirror=0 owner_repo="" visibility=""
  effective_url="$(git -C "$MIRROR_DIR" remote get-url origin 2>/dev/null || true)"
  case "$remote_url" in
    *github*) gh_source_url="$remote_url" ;;
  esac
  if [[ -z "$gh_source_url" ]]; then
    case "$effective_url" in
      *github*) gh_source_url="$effective_url" ;;
    esac
  fi
  if [[ -n "$gh_source_url" ]]; then
    github_mirror=1
    owner_repo="$(echo "$gh_source_url" | sed -n 's|.*[:/]\([^/:]*/[^/:]*\)$|\1|p')"
    owner_repo="${owner_repo%.git}"
  fi
  if [[ "$github_mirror" -eq 1 ]]; then
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
      visibility="$(gh repo view "$owner_repo" --json visibility -q .visibility 2>/dev/null || true)"
    fi
    case "$visibility" in
      PRIVATE|private)
        echo "  [ok] Mirror repo is private ($owner_repo)."
        ;;
      PUBLIC|public)
        echo "  STOP: the mirror repo is PUBLIC. Make it private FIRST so the old"
        echo "  history stops being served while you rewrite it:"
        echo "    https://github.com/$owner_repo/settings"
        echo "    (Danger Zone > Change repository visibility > Private)"
        echo "  Your squares still count afterwards: enable 'Include private"
        echo "  contributions' at https://github.com/settings/profile"
        echo "  Nothing was changed. Re-run greens --privacy-migrate once private."
        exit 1
        ;;
      *)
        echo "  STOP: can't verify the mirror repo's visibility, so refusing to"
        echo "  proceed (fail closed). To fix:"
        echo "    1. Install the GitHub CLI:  brew install gh"
        echo "    2. Authenticate your PERSONAL account:  gh auth login"
        echo "    3. Re-run:  greens --privacy-migrate"
        echo "  Nothing was changed."
        exit 1
        ;;
    esac
  else
    echo "  [i] Non-GitHub remote ($masked_url) — repo-visibility check not applicable."
  fi

  # ── Step 3: fetch everything advertised; snapshot EVERY remote ref ───────
  # ALL refs, not just heads/tags: a custom ref (refs/notes/..., refs/x/...)
  # pointing at the legacy tip would otherwise keep the old README fetchable
  # after a "successful" migration.
  local fetch_out
  if ! fetch_out="$(git -C "$MIRROR_DIR" fetch --prune origin "+refs/heads/*:refs/remotes/origin/*" "+refs/*:refs/greens-remote-scan/*" 2>&1)"; then
    echo "  ERROR: couldn't fetch the mirror's refs:"
    echo "$fetch_out" | tail -3 | sed 's/^/    /'
    echo "  Nothing was changed."
    exit 1
  fi
  local tmp_snapshot
  tmp_snapshot="$(mktemp)"
  if ! git -C "$MIRROR_DIR" ls-remote origin > "$tmp_snapshot.raw" 2>/dev/null; then
    echo "  ERROR: couldn't list the mirror's remote refs. Nothing was changed."
    rm -f "$tmp_snapshot" "$tmp_snapshot.raw"
    exit 1
  fi
  # Drop peeled annotated-tag lines (^{}) and the HEAD symref pseudo-ref.
  grep -v '\^{}' "$tmp_snapshot.raw" | awk '$2 != "HEAD"' > "$tmp_snapshot" || true
  rm -f "$tmp_snapshot.raw"

  # Fresh, unborn remote: nothing ever pushed — already clean.
  if [[ ! -s "$tmp_snapshot" ]]; then
    echo "  The mirror remote has no refs (fresh repo). Nothing to migrate."
    rm -f "$tmp_snapshot"
    exit 0
  fi

  if [[ -z "$default_branch" ]]; then
    # Some remotes (e.g. bare repos whose HEAD points at an unborn branch)
    # don't advertise a symref. A single existing head is the default in
    # practice — anything else is genuinely ambiguous.
    if [[ "$(grep -c 'refs/heads/' "$tmp_snapshot")" == "1" ]]; then
      default_branch="$(awk '$2 ~ /^refs\/heads\// {sub("refs/heads/", "", $2); print $2; exit}' "$tmp_snapshot")"
      echo "  [i] Remote advertises no HEAD symref; using its only branch: $default_branch"
    else
      echo "  ERROR: the remote has refs but no detectable default branch (HEAD"
      echo "  symref). Fix the repo's default branch on GitHub, then re-run."
      rm -f "$tmp_snapshot"
      exit 1
    fi
  fi

  local db_ref="refs/heads/$default_branch"
  local src_ref="refs/remotes/origin/$default_branch"
  local db_old_oid
  db_old_oid="$(awk -v ref="$db_ref" '$2 == ref {print $1; exit}' "$tmp_snapshot")"

  local empty_tree
  empty_tree="$(git -C "$MIRROR_DIR" hash-object -t tree /dev/null)"

  # ── Step 3b: already-migrated audit (idempotency) ─────────────────────────
  # Detector is the fetched remote state itself, not a config marker: the
  # COMPLETE advertised ref set is exactly the default branch (no stray
  # heads/tags/notes/custom refs), a linear chain of empty-tree commits with
  # the sanitized identity, and no README blob anywhere.
  local ref_count
  ref_count="$(wc -l < "$tmp_snapshot" | tr -d ' ')"
  if [[ "$ref_count" -eq 1 ]] && [[ -n "$db_old_oid" ]] && \
     git -C "$MIRROR_DIR" rev-parse --verify --quiet "$src_ref" >/dev/null 2>&1; then
    local audit_clean=1
    # linear chain (no merges)
    if [[ -n "$(git -C "$MIRROR_DIR" rev-list --min-parents=2 "$src_ref" 2>/dev/null | head -1)" ]]; then
      audit_clean=0
    fi
    # every tree is the empty tree
    if [[ "$(git -C "$MIRROR_DIR" log --format='%T' "$src_ref" | LC_ALL=C sort -u)" != "$empty_tree" ]]; then
      audit_clean=0
    fi
    # sanitized identities and author==committer dates throughout
    if [[ "$audit_clean" -eq 1 ]]; then
      local ident_lines expected_ident
      expected_ident="$(printf '%s\t%s\t%s\t%s' "$MIRROR_NAME" "$MIRROR_EMAIL" "$MIRROR_NAME" "$MIRROR_EMAIL")"
      ident_lines="$(git -C "$MIRROR_DIR" log --format='%an%x09%ae%x09%cn%x09%ce' "$src_ref" | LC_ALL=C sort -u)"
      if [[ "$ident_lines" != "$expected_ident" ]]; then
        audit_clean=0
      fi
      if git -C "$MIRROR_DIR" log --format='%at %ct' "$src_ref" | awk '$1 != $2 {exit 1}'; then :; else
        audit_clean=0
      fi
    fi
    if [[ "$audit_clean" -eq 1 ]]; then
      echo "  Mirror already uses privacy-safe v1.8.2 history; nothing to migrate."
      # Reconcile local state in case a previous run died after the push:
      # local checkout, COPY_MESSAGES, history marker, stamp.
      if [[ "$(git -C "$MIRROR_DIR" rev-parse --verify --quiet HEAD 2>/dev/null || true)" != "$db_old_oid" ]] || \
         [[ "$(scan_repo_readme_state "$MIRROR_DIR")" != "none" ]]; then
        echo "  Reconciling the local mirror checkout with the migrated remote..."
        replace_mirror_with_clean_clone "$remote_url" "$default_branch" || exit 1
      fi
      # Every migration-concluding path persists COPY_MESSAGES=0, always —
      # including this reconcile-after-interrupt path and regardless of
      # --keep-messages (which only governs the rewritten history's content;
      # a rerun never re-collected the double-ack).
      config_upsert "COPY_MESSAGES" 'COPY_MESSAGES="${COPY_MESSAGES:-0}"'
      config_upsert "GREENS_HISTORY_FORMAT" 'GREENS_HISTORY_FORMAT="${GREENS_HISTORY_FORMAT:-2}"'
      rm -f "$tmp_snapshot"
      exit 0
    fi
  fi

  if ! git -C "$MIRROR_DIR" rev-parse --verify --quiet "$src_ref" >/dev/null 2>&1; then
    echo "  ERROR: the remote default branch ($default_branch) has no commits"
    echo "  locally after fetch. Nothing was changed."
    rm -f "$tmp_snapshot"
    exit 1
  fi

  # ── Step 4: classify ALL reachable content before touching anything ──────
  echo "  Verifying the mirror only contains greens-generated content..."

  # 4a0. Every advertised ref (default branch aside) must peel to a COMMIT in
  # the fetched, content-validated history — those are greens-managed strays
  # (old branches, tags, custom refs at the legacy tip) and get pruned in the
  # atomic push. Anything that peels to a blob/tree or an unknown object is
  # user content: ABORT before any mutation.
  local snap_oid snap_ref peeled_commit
  while IFS=$'\t' read -r snap_oid snap_ref; do
    [[ -z "$snap_ref" ]] && continue
    [[ "$snap_ref" == "$db_ref" ]] && continue
    peeled_commit="$(git -C "$MIRROR_DIR" rev-parse --verify --quiet "${snap_oid}^{commit}" 2>/dev/null || true)"
    if [[ -z "$peeled_commit" ]]; then
      echo ""
      echo "  ABORT: remote ref $snap_ref does not point at commit history greens"
      echo "  manages (it targets a non-commit or unknown object). Refusing to"
      echo "  rewrite or delete user content. Nothing was changed."
      echo "  Move that ref's content elsewhere, delete the ref on the remote,"
      echo "  then re-run greens --privacy-migrate."
      rm -f "$tmp_snapshot"
      exit 1
    fi
  done < "$tmp_snapshot"

  # 4a. Foreign-content scan across every reachable commit tree (all refs):
  # a tree must be empty or contain exactly the generated root README.md.
  local tree listing entry_count entry_name blob content
  while IFS= read -r tree; do
    [[ -z "$tree" ]] && continue
    listing="$(git -C "$MIRROR_DIR" ls-tree "$tree" 2>/dev/null || true)"
    [[ -z "$listing" ]] && continue
    entry_count="$(printf '%s\n' "$listing" | wc -l | tr -d ' ')"
    entry_name="$(printf '%s\n' "$listing" | head -1 | awk '{print $4}')"
    if [[ "$entry_count" != "1" ]] || [[ "$entry_name" != "README.md" ]]; then
      echo ""
      echo "  ABORT: the mirror history contains paths greens didn't create:"
      printf '%s\n' "$listing" | awk '{print "    - " $4}' | head -10
      echo ""
      echo "  --privacy-migrate only rewrites mirrors that greens fully manages"
      echo "  (empty commits plus its own generated README). Nothing was changed."
      echo "  Move your own files to another repo, or start a fresh private"
      echo "  mirror with 'greens --setup'."
      rm -f "$tmp_snapshot"
      exit 1
    fi
    blob="$(printf '%s\n' "$listing" | head -1 | awk '{print $3}')"
    content="$(git -C "$MIRROR_DIR" cat-file blob "$blob" 2>/dev/null || true)"
    if ! is_generated_readme_content "$content"; then
      echo ""
      echo "  ABORT: the mirror history contains a README.md greens didn't generate."
      echo "  Refusing to rewrite user content. Nothing was changed."
      echo "  Preserve your README elsewhere, or start a fresh private mirror"
      echo "  with 'greens --setup'."
      rm -f "$tmp_snapshot"
      exit 1
    fi
  done < <(git -C "$MIRROR_DIR" log --all --format='%T' 2>/dev/null | LC_ALL=C sort -u)

  # 4b. Build the migration manifest from the OLD REMOTE DEFAULT BRANCH.
  # Structural classification:
  #   - drop the legacy root init: no parent + empty tree + exact subject "init"
  #   - drop generated status commits: exact subject "Update sync status" AND
  #     the diff against the parent touches only root README.md AND the
  #     resulting blob matches the generator signature
  #   - retain everything else (activity commits KEEP their timestamps even
  #     when their trees carry the README — the rebuild empties the tree)
  # Parsing note: tab is IFS whitespace in bash, so ADJACENT tabs collapse and
  # an empty %P (root commit) would shift every following field. bash 3.2's
  # read also can't split on control-char IFS. So the parent field carries a
  # literal "p" prefix — no field is ever empty, no tabs ever collapse.
  # Manifest: author_epoch, ordinal, author_off, committer_epoch,
  #           committer_off, subject (last — may contain tabs)
  local tmp_manifest tmp_expected_tuples
  tmp_manifest="$(mktemp)"
  tmp_expected_tuples="$(mktemp)"
  local ordinal=0 retained=0 dropped_init=0 dropped_status=0
  local H T P at ai ct ci subj aoff coff changed rblob rcontent drop
  while IFS=$'\t' read -r H T P at ai ct ci subj; do
    [[ -z "$H" ]] && continue
    P="${P#p}"
    ordinal=$((ordinal + 1))
    case "$P" in
      *" "*)
        echo ""
        echo "  ABORT: merge commit found ($H) — greens never creates merges, so"
        echo "  this history is not greens-managed. Nothing was changed."
        rm -f "$tmp_snapshot" "$tmp_manifest" "$tmp_expected_tuples"
        exit 1
        ;;
    esac
    drop=0
    if [[ -z "$P" && "$subj" == "init" && "$T" == "$empty_tree" ]]; then
      drop=1
      dropped_init=$((dropped_init + 1))
    elif [[ "$subj" == "Update sync status" ]]; then
      if [[ -n "$P" ]]; then
        changed="$(git -C "$MIRROR_DIR" diff-tree --no-commit-id --no-renames --name-only -r "$H" 2>/dev/null || true)"
      else
        changed="$(git -C "$MIRROR_DIR" ls-tree --name-only "$T" 2>/dev/null || true)"
      fi
      rblob="$(git -C "$MIRROR_DIR" rev-parse --verify --quiet "$H:README.md" 2>/dev/null || true)"
      rcontent=""
      [[ -n "$rblob" ]] && rcontent="$(git -C "$MIRROR_DIR" cat-file blob "$rblob" 2>/dev/null || true)"
      if [[ "$changed" == "README.md" ]] && [[ -n "$rblob" ]] && is_generated_readme_content "$rcontent"; then
        drop=1
        dropped_status=$((dropped_status + 1))
      fi
    fi
    if [[ "$drop" -eq 0 ]]; then
      aoff="${ai##* }"
      coff="${ci##* }"
      printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$at" "$ordinal" "$aoff" "$ct" "$coff" "$subj" >> "$tmp_manifest"
      printf '%s\t%s\t%s\t%s\n' "$at" "$ai" "$ct" "$ci" >> "$tmp_expected_tuples"
      retained=$((retained + 1))
    fi
  done < <(git -C "$MIRROR_DIR" log --reverse --topo-order --format='%H%x09%T%x09p%P%x09%at%x09%ai%x09%ct%x09%ci%x09%s' "$src_ref")

  local total_count
  total_count="$(git -C "$MIRROR_DIR" rev-list --count "$src_ref")"

  if [[ "$retained" -eq 0 ]]; then
    echo ""
    echo "  STOP: no real activity exists to rebuild — this mirror holds only"
    echo "  greens' synthetic init/status commits ($total_count total)."
    echo "  greens will not create a replacement init commit. Remedy: delete the"
    echo "  mirror repo on GitHub and run 'greens --setup' to create a clean"
    echo "  private mirror; the first real activity commit becomes its root."
    rm -f "$tmp_snapshot" "$tmp_manifest" "$tmp_expected_tuples"
    exit 1
  fi

  # Deterministic order: ascending author epoch, tie-broken by the original
  # topological ordinal. Numeric keys, C locale, and NO -u — same-second
  # commits and same-epoch-different-offset commits must all survive.
  local tmp_sorted_manifest sep_char
  tmp_sorted_manifest="$(mktemp)"
  sep_char="$(printf '\t')"
  LC_ALL=C sort -t "$sep_char" -k1,1n -k2,2n "$tmp_manifest" > "$tmp_sorted_manifest"

  # Stale refs (anything advertised besides the default branch) get deleted in
  # the same atomic push. Count/list for the plan summary.
  local tmp_stale stale_count
  tmp_stale="$(mktemp)"
  awk -v ref="$db_ref" '$2 != ref {print $1 "\t" $2}' "$tmp_snapshot" > "$tmp_stale"
  stale_count="$(wc -l < "$tmp_stale" | tr -d ' ')"

  # ── Step 5: plan summary + typed confirmations ────────────────────────────
  echo ""
  echo "  Mirror:   $MIRROR_DIR"
  echo "  Remote:   $masked_url"
  echo "  Branch:   $default_branch"
  echo "  Commits:  $total_count on the remote default branch"
  echo "            -> keeping $retained activity commits"
  echo "            -> dropping $dropped_init init + $dropped_status status commits (greens' own)"
  if [[ "$stale_count" -gt 0 ]]; then
    echo "  Stale refs to DELETE from the remote (still hold old history):"
    sed 's/^[^\t]*\t/    - /' "$tmp_stale"
  fi
  echo ""
  echo "  This REWRITES the mirror's remote history in one atomic push:"
  echo "    - README.md (which listed your work repo names) is removed from the"
  echo "      rewritten remote history and all fresh clones"
  echo "    - every commit re-authored as: $MIRROR_NAME <$MIRROR_EMAIL>"
  if [[ "$keep_messages" -eq 1 ]]; then
    echo "    - commit messages KEPT (--keep-messages), except legacy PR/review/"
    echo "      issue titles, which become generic labels"
  else
    echo "    - every commit message redacted to \"sync\""
  fi
  echo "    - author AND committer timestamps preserved exactly (epoch + offset):"
  echo "      your contribution graph does not change"
  echo "    - a private local backup bundle of the old history is written first"
  echo ""
  echo "  A rewrite cannot recall copies that already left the repo: clones,"
  echo "  forks, old-SHA URLs, caches, screenshots, or provider retention. The"
  echo "  old history is removed from the rewritten remote and fresh clones,"
  echo "  not erased everywhere."
  echo ""

  if [[ "$keep_messages" -eq 1 ]]; then
    echo "  --keep-messages retains raw git commit subjects. They can contain"
    echo "  client, project, and ticket names; merge subjects commonly contain"
    echo "  org/branch/repo names. No sanitizer is applied. Legacy \"PR: \","
    echo "  \"Review: \", \"Issue: \" titles become generic labels (a real subject"
    echo "  that starts with one of those prefixes is converted too — ambiguous"
    echo "  by construction). Future syncs still reset to timestamps-only."
    printf "  Type KEEP MESSAGES to confirm keeping subjects: " >&2
    local keep_reply=""
    read -r keep_reply || true
    if [[ "$keep_reply" != "KEEP MESSAGES" ]]; then
      echo "  Not confirmed. Nothing was changed. Re-run without --keep-messages"
      echo "  to redact everything to \"sync\"."
      rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale"
      exit 1
    fi
    echo ""
  fi

  printf "  Type YES to rewrite and force-push: " >&2
  local reply=""
  read -r reply || true
  if [[ "$reply" != "YES" ]]; then
    echo "  Cancelled. Nothing was changed."
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale"
    exit 0
  fi

  # ── Step 6: private local backup bundle (never pushed anywhere) ───────────
  local backup_dir="$HOME/.contrib-mirror/backups"
  mkdir -p "$backup_dir"
  chmod 700 "$backup_dir" 2>/dev/null || true
  local bundle_file
  bundle_file="$backup_dir/mirror-pre-migrate-$(date '+%Y%m%d-%H%M%S').bundle"
  echo ""
  echo "  Writing local backup bundle..."
  if ! git -C "$MIRROR_DIR" bundle create "$bundle_file" --all >/dev/null 2>&1; then
    echo "  ERROR: couldn't create the backup bundle. Nothing was changed."
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale"
    exit 1
  fi
  chmod 600 "$bundle_file" 2>/dev/null || true
  if ! git -C "$MIRROR_DIR" bundle verify "$bundle_file" >/dev/null 2>&1; then
    echo "  ERROR: backup bundle failed verification. Nothing was changed."
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale" "$bundle_file"
    exit 1
  fi
  echo "  [ok] Backup bundle: $bundle_file"
  echo "       It contains the OLD sensitive history (repo names/messages)."
  echo "       It stays local — never upload or push it anywhere."

  # ── Step 7: build the new chain with commit-tree in a scratch repo ────────
  # commit-tree against one computed empty-tree OID makes "README absent from
  # every tree" an invariant of construction, not a cleanup step.
  local tmp_build
  tmp_build="$(mktemp -d)"
  git -C "$tmp_build" init --quiet
  git -C "$tmp_build" symbolic-ref HEAD "$db_ref"
  local build_empty_tree
  build_empty_tree="$(git -C "$tmp_build" hash-object -w -t tree /dev/null)"

  echo ""
  echo "  Rebuilding $retained commits (author+committer dates preserved)..."
  local built=0 parent="" new_oid="" msg
  while IFS=$'\t' read -r at ordinal aoff ct coff subj; do
    [[ -z "$at" ]] && continue
    if [[ "$keep_messages" -eq 1 ]]; then
      case "$subj" in
        "PR: "*)     msg="PR activity" ;;
        "Review: "*) msg="Review activity" ;;
        "Issue: "*)  msg="Issue activity" ;;
        "")          msg="sync" ;;
        *)           msg="$subj" ;;
      esac
    else
      msg="sync"
    fi
    if [[ -n "$parent" ]]; then
      new_oid="$(GIT_AUTHOR_NAME="$MIRROR_NAME" GIT_AUTHOR_EMAIL="$MIRROR_EMAIL" \
        GIT_AUTHOR_DATE="@${at} ${aoff}" \
        GIT_COMMITTER_NAME="$MIRROR_NAME" GIT_COMMITTER_EMAIL="$MIRROR_EMAIL" \
        GIT_COMMITTER_DATE="@${ct} ${coff}" \
        git -C "$tmp_build" -c user.name="$MIRROR_NAME" -c user.email="$MIRROR_EMAIL" \
          commit-tree "$build_empty_tree" -p "$parent" -m "$msg")"
    else
      new_oid="$(GIT_AUTHOR_NAME="$MIRROR_NAME" GIT_AUTHOR_EMAIL="$MIRROR_EMAIL" \
        GIT_AUTHOR_DATE="@${at} ${aoff}" \
        GIT_COMMITTER_NAME="$MIRROR_NAME" GIT_COMMITTER_EMAIL="$MIRROR_EMAIL" \
        GIT_COMMITTER_DATE="@${ct} ${coff}" \
        git -C "$tmp_build" -c user.name="$MIRROR_NAME" -c user.email="$MIRROR_EMAIL" \
          commit-tree "$build_empty_tree" -m "$msg")"
    fi
    parent="$new_oid"
    built=$((built + 1))
    if [[ $((built % 500)) -eq 0 ]]; then
      echo "    ...$built/$retained"
    fi
  done < "$tmp_sorted_manifest"
  git -C "$tmp_build" update-ref "$db_ref" "$parent"
  echo "  [ok] Rebuilt $built commits."

  # ── Step 8: verify the new chain COMPLETELY before any network mutation ──
  local verify_fail=0
  if [[ "$built" -ne "$retained" ]]; then
    echo "  VERIFY FAIL: built $built commits, expected $retained."
    verify_fail=1
  fi
  if [[ "$(git -C "$tmp_build" rev-list --count "$db_ref")" != "$retained" ]]; then
    echo "  VERIFY FAIL: new chain length mismatch."
    verify_fail=1
  fi
  if [[ -n "$(git -C "$tmp_build" rev-list --min-parents=2 "$db_ref" | head -1)" ]]; then
    echo "  VERIFY FAIL: new chain is not linear."
    verify_fail=1
  fi
  if [[ "$(git -C "$tmp_build" log --format='%T' "$db_ref" | LC_ALL=C sort -u)" != "$build_empty_tree" ]]; then
    echo "  VERIFY FAIL: a rebuilt commit does not use the empty tree."
    verify_fail=1
  fi
  local expected_ident
  expected_ident="$(printf '%s\t%s\t%s\t%s' "$MIRROR_NAME" "$MIRROR_EMAIL" "$MIRROR_NAME" "$MIRROR_EMAIL")"
  if [[ "$(git -C "$tmp_build" log --format='%an%x09%ae%x09%cn%x09%ce' "$db_ref" | LC_ALL=C sort -u)" != "$expected_ident" ]]; then
    echo "  VERIFY FAIL: identity not fully sanitized."
    verify_fail=1
  fi
  if git -C "$tmp_build" rev-list --objects "$db_ref" | awk '$2 != "" {exit 1}'; then :; else
    echo "  VERIFY FAIL: a path is reachable in the new history."
    verify_fail=1
  fi
  # Full date-tuple multiset (author epoch+string, committer epoch+string),
  # duplicates preserved — compare sorted WITHOUT -u.
  local tmp_new_tuples
  tmp_new_tuples="$(mktemp)"
  git -C "$tmp_build" log --format='%at%x09%ai%x09%ct%x09%ci' "$db_ref" > "$tmp_new_tuples"
  if ! diff <(LC_ALL=C sort "$tmp_expected_tuples") <(LC_ALL=C sort "$tmp_new_tuples") >/dev/null 2>&1; then
    echo "  VERIFY FAIL: date tuples changed during the rebuild."
    verify_fail=1
  fi
  if [[ "$keep_messages" -ne 1 ]]; then
    if [[ "$(git -C "$tmp_build" log --format='%s' "$db_ref" | LC_ALL=C sort -u)" != "sync" ]]; then
      echo "  VERIFY FAIL: a message other than \"sync\" survived."
      verify_fail=1
    fi
  fi
  if [[ "$verify_fail" -ne 0 ]]; then
    echo "  ERROR: pre-push verification failed. The remote was NOT touched."
    echo "  Old local mirror and backup bundle are intact: $bundle_file"
    rm -rf "$tmp_build"
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale" "$tmp_new_tuples"
    exit 1
  fi
  echo "  [ok] New chain verified (count, dates, identity, empty trees, messages)."

  # ── Step 9: one atomic push — exact leases on EVERY advertised ref ───────
  # Updates the default branch and deletes all stale heads/tags in a single
  # transaction. Explicit refspecs only; never push --mirror (it would publish
  # local tracking/backup refs). If the server can't do atomic, we abort — no
  # sequential fallback.
  git -C "$tmp_build" remote add origin "$remote_url"
  chmod 600 "$tmp_build/.git/config" 2>/dev/null || true

  # push_args is never empty (--atomic + default-branch refspec at minimum),
  # so plain expansion is bash-3.2-safe; += appends never expand the array.
  local push_args
  push_args=(--atomic)
  if [[ -n "$db_old_oid" ]]; then
    push_args+=("--force-with-lease=$db_ref:$db_old_oid")
  else
    push_args+=("--force-with-lease=$db_ref:")
  fi
  push_args+=("$db_ref:$db_ref")
  local stale_oid stale_ref
  while IFS=$'\t' read -r stale_oid stale_ref; do
    [[ -z "$stale_ref" ]] && continue
    push_args+=("--force-with-lease=$stale_ref:$stale_oid" ":$stale_ref")
  done < "$tmp_stale"

  echo "  Pushing (atomic, force-with-lease on every ref)..."
  local push_out push_rc=0
  push_out="$(git -C "$tmp_build" push origin "${push_args[@]}" 2>&1)" || push_rc=$?

  # ── Step 10: verify the REMOTE state — never trust the client exit alone ──
  # The COMPLETE advertised ref set must now be exactly the default branch.
  local tmp_after new_tip after_query_ok=1
  tmp_after="$(mktemp)"
  new_tip="$(git -C "$tmp_build" rev-parse "$db_ref")"
  if git -C "$tmp_build" ls-remote origin > "$tmp_after.raw" 2>/dev/null; then
    grep -v '\^{}' "$tmp_after.raw" | awk '$2 != "HEAD"' > "$tmp_after" || true
  else
    after_query_ok=0
  fi
  rm -f "$tmp_after.raw"
  if [[ "$after_query_ok" -ne 1 ]]; then
    echo "  ERROR: push finished with status $push_rc but the remote can't be"
    echo "  queried to confirm the result. Re-run greens --privacy-migrate once"
    echo "  the remote is reachable — it reconciles a half-finished migration."
    echo "$push_out" | tail -5 | sed 's/^/    /'
    rm -rf "$tmp_build"
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale" "$tmp_new_tuples" "$tmp_after"
    exit 1
  fi
  local after_ok=1
  if [[ "$(wc -l < "$tmp_after" | tr -d ' ')" != "1" ]]; then after_ok=0; fi
  if [[ "$(awk -v ref="$db_ref" '$2 == ref {print $1; exit}' "$tmp_after")" != "$new_tip" ]]; then after_ok=0; fi
  if [[ "$after_ok" -ne 1 ]]; then
    if [[ "$push_rc" -ne 0 ]]; then
      echo "  ERROR: atomic push was rejected; the remote still has the OLD history."
      echo "$push_out" | tail -5 | sed 's/^/    /'
      # NOTE: a lease rejection under --atomic also prints "atomic push failed",
      # so the stale-lease pattern must be checked first.
      case "$push_out" in
        *"stale info"*|*lease*)
          echo "  (A ref moved since the snapshot — something else pushed. Fetch,"
          echo "  review what arrived, and re-run greens --privacy-migrate.)" ;;
        *"does not support --atomic"*|*"does not support atomic"*)
          echo "  (The server doesn't support atomic pushes; greens will not fall"
          echo "  back to a non-atomic sequence.)" ;;
      esac
      echo "  Nothing further was changed. Backup bundle: $bundle_file"
    else
      echo "  ERROR: the remote does not match the expected rewritten state."
      echo "  Inspect it manually before re-running. Backup bundle: $bundle_file"
      cat "$tmp_after" | sed 's/^/    /'
    fi
    rm -rf "$tmp_build"
    rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale" "$tmp_new_tuples" "$tmp_after"
    exit 1
  fi
  if [[ "$push_rc" -ne 0 ]]; then
    echo "  [i] The push client reported failure (status $push_rc), but the remote"
    echo "      matches the fully verified new state — treating the push as applied."
  fi
  echo "  [ok] Remote rewritten and verified: $default_branch -> ${new_tip:0:12}, no stale refs."

  # ── Step 11: finalize locally (only after verified remote success) ────────
  local old_backup="${MIRROR_DIR}.pre-migrate.$$"
  if ! mv "$MIRROR_DIR" "$old_backup"; then
    echo "  [!] Remote migration SUCCEEDED, but the old local mirror couldn't be"
    echo "      moved aside. Replace $MIRROR_DIR with the rewritten repo at:"
    echo "      $tmp_build  (or re-run greens --privacy-migrate to reconcile)"
    exit 1
  fi
  if mv "$tmp_build" "$MIRROR_DIR"; then
    rm -rf "$old_backup"
    echo "  [ok] Local mirror replaced; old local refs pruned."
  else
    mv "$old_backup" "$MIRROR_DIR" 2>/dev/null || true
    echo "  [!] Remote migration SUCCEEDED, but the local swap failed. The"
    echo "      rewritten repo is at: $tmp_build — replace $MIRROR_DIR with it,"
    echo "      or re-run greens --privacy-migrate to reconcile."
    exit 1
  fi

  # Future syncs are timestamps-only regardless of --keep-messages; keeping
  # old subjects is a migration-time exception, not a go-forward mode.
  config_upsert "COPY_MESSAGES" 'COPY_MESSAGES="${COPY_MESSAGES:-0}"'
  config_upsert "GREENS_HISTORY_FORMAT" 'GREENS_HISTORY_FORMAT="${GREENS_HISTORY_FORMAT:-2}"'
  echo "  [ok] COPY_MESSAGES set to 0 (timestamps only) in config."

  rm -f "${LOG_DIR:-$HOME/.contrib-mirror/logs}/last-success-date" "$SCRIPT_DIR/logs/last-success-date" 2>/dev/null || true
  rm -f "$tmp_snapshot" "$tmp_sorted_manifest" "$tmp_manifest" "$tmp_expected_tuples" "$tmp_stale" "$tmp_new_tuples" "$tmp_after"

  echo ""
  echo "  Done. The old README/identities/messages are removed from the"
  echo "  rewritten remote history and fresh clones. They still exist in: your"
  echo "  local backup bundle, any old clones/forks, old-SHA URLs, caches, and"
  echo "  screenshots — a rewrite is cleanup, not erasure."
  echo "  Next 'greens' sync continues from the rewritten history. Note: on a"
  echo "  verified-PRIVATE mirror the next sync writes a fresh dashboard README"
  echo "  (repo names, owner-visible by design); on public or unverified"
  echo "  mirrors the repo-names table is never written."
  exit 0
}

# Replace the local mirror checkout with a fresh clone of the (already
# migrated) remote. Used by the idempotent reconcile path.
replace_mirror_with_clean_clone() {
  local url="$1" branch="$2" tmp_clone
  tmp_clone="$(mktemp -d)/mirror"
  if ! git clone --quiet --branch "$branch" "$url" "$tmp_clone" 2>/dev/null; then
    echo "  [!] Couldn't re-clone the migrated remote; local mirror left as-is."
    return 1
  fi
  chmod 600 "$tmp_clone/.git/config" 2>/dev/null || true
  local old_backup="${MIRROR_DIR}.pre-reconcile.$$"
  if ! mv "$MIRROR_DIR" "$old_backup"; then
    echo "  [!] Couldn't move the old local mirror aside; left as-is."
    rm -rf "$(dirname "$tmp_clone")"
    return 1
  fi
  if mv "$tmp_clone" "$MIRROR_DIR"; then
    rm -rf "$old_backup" "$(dirname "$tmp_clone")" 2>/dev/null || true
    echo "  [ok] Local mirror reconciled with the migrated remote."
    return 0
  fi
  mv "$old_backup" "$MIRROR_DIR" 2>/dev/null || true
  rm -rf "$(dirname "$tmp_clone")" 2>/dev/null || true
  echo "  [!] Local reconcile failed; left as-is."
  return 1
}

# CLI flags
case "${1:-}" in
  --setup|init)   exec "$SCRIPT_DIR/setup.sh" ;;
  sync)      ;; # alias: greens sync = greens (default)
  --help|-h) echo "Usage: greens [sync|init|--setup|--status|--resync|--privacy-migrate|--reset|--help|--version]"
             echo "  sync       Run sync (default, same as bare greens)"
             echo "  init       Run interactive setup wizard (alias for --setup)"
             echo "  --setup    Run interactive setup wizard"
             echo "  --status   Show current config and sync status"
             echo "  --resync   Wipe mirror history (local + remote) and sync fresh"
             echo "  --privacy-migrate [--keep-messages]"
             echo "             Scrub the mirror history: rewrite it so the dashboard README,"
             echo "             old identities and copied messages are removed from the"
             echo "             rewritten remote history and fresh clones (local backup"
             echo "             bundle kept). Recommended if the mirror was ever public."
             echo "             --keep-messages retains raw commit subjects (extra typed ack)."
             echo "  --reset    Remove config, caches, and scheduler"
             echo "  --version  Show version"
             echo "  --help     Show this help"
             exit 0 ;;
  --privacy-migrate)
    shift
    privacy_migrate "$@"
    ;;
  --resync)
    echo "greens — resync"
    echo ""
    echo "  This will wipe all mirror commits (local + remote) and sync fresh."
    printf "  Continue? [y/N]: " >&2
    read -r reply
    if [[ ! "$reply" =~ ^[Yy] ]]; then
      echo "  Cancelled."
      exit 0
    fi
    source "$CONFIG_FILE" 2>/dev/null || { echo "  No config found. Run: greens"; exit 1; }
    MIRROR_DIR="${MIRROR_DIR:-$HOME/.contrib-mirror/mirror}"
    # Legacy history must be migrated, not resynced over. (The sync this
    # execs at the end re-checks against the refreshed remote as well.)
    if [[ -d "$MIRROR_DIR/.git" ]] && [[ "$(scan_repo_readme_state "$MIRROR_DIR")" == "generated" ]]; then
      legacy_refuse
    fi
    # Save the raw configured remote URL before wiping (not get-url, which
    # applies insteadOf rewrites — keep the user's configured URL intact)
    remote_url=""
    if [[ -d "$MIRROR_DIR/.git" ]]; then
      remote_url="$(git -C "$MIRROR_DIR" config remote.origin.url 2>/dev/null || true)"
    fi
    if [[ -z "$remote_url" ]]; then
      echo "  No remote URL found in mirror repo."
      printf "  Enter mirror repo URL (with token if HTTPS): " >&2
      read -r remote_url
      if [[ -z "$remote_url" ]]; then
        echo "  Cancelled."
        exit 1
      fi
    fi
    # Match the remote's default branch so the forced push lands where
    # GitHub counts contributions. No main/master guessing: symref first,
    # then the remote's only branch; a truly unborn remote keeps git's own
    # init default (the first push defines the branch).
    default_branch="$(git ls-remote --symref "$remote_url" HEAD 2>/dev/null | awk '/^ref:/ {sub("refs/heads/", "", $2); print $2; exit}')"
    if [[ -z "$default_branch" ]]; then
      default_branch="$(git ls-remote --heads "$remote_url" 2>/dev/null | awk 'NR==1 {sub("refs/heads/", "", $2); print $2}')"
    fi
    # Wipe and re-init mirror. No init commit — the first mirrored activity
    # commit becomes the new root.
    rm -rf "$MIRROR_DIR"
    mkdir -p "$MIRROR_DIR"
    git -C "$MIRROR_DIR" init --quiet
    if [[ -n "$default_branch" ]]; then
      git -C "$MIRROR_DIR" symbolic-ref HEAD "refs/heads/$default_branch"
    fi
    git -C "$MIRROR_DIR" remote add origin "$remote_url"
    chmod 600 "$MIRROR_DIR/.git/config" 2>/dev/null || true
    # Verify the remote is reachable (the actual push happens after the sync
    # below rebuilds the commits, with --force to overwrite remote history).
    if ! git -C "$MIRROR_DIR" ls-remote origin >/dev/null 2>&1; then
      echo "  [!] Can't reach the mirror remote. Re-run 'greens --setup' for access."
      exit 1
    fi
    echo "  [ok] Mirror re-initialized (branch: ${default_branch:-<remote is empty; first push defines it>})."
    # Delete stamp so sync runs
    rm -f "${LOG_DIR:-$HOME/.contrib-mirror/logs}/last-success-date" "$SCRIPT_DIR/logs/last-success-date" 2>/dev/null
    echo "  [ok] Starting fresh sync (remote history is overwritten on push)..."
    echo ""
    FORCE=1 GREENS_PUSH_FORCE=1 exec "$0"
    ;;
  --version) echo "greens $VERSION"; exit 0 ;;
  --status)
    echo "greens $VERSION"
    echo ""
    if [[ ! -f "$CONFIG_FILE" ]]; then
      echo "  Not configured. Run: greens"
      exit 0
    fi
    source "$CONFIG_FILE"
    echo "  Config:       $CONFIG_FILE"
    echo "  Work dir:     ${WORK_DIR:-not set}"
    if [[ -d "${WORK_DIR:-}" ]]; then
      repo_count="$(find "$WORK_DIR" -maxdepth 2 -name .git -print 2>/dev/null | wc -l | tr -d ' ')"
      echo "  Repos found:  $repo_count"
    fi
    echo "  Remote prefix: ${REMOTE_PREFIX:-not set}"
    echo "  Emails:       ${EMAILS:-not set}"
    echo "  Mirror dir:   ${MIRROR_DIR:-not set}"
    if [[ -d "${MIRROR_DIR:-}" ]] && [[ -d "${MIRROR_DIR}/.git" ]]; then
      mirror_commits="$(git -C "$MIRROR_DIR" rev-list --count HEAD 2>/dev/null || echo "0")"
      echo "  Mirror commits: $mirror_commits"
      if [[ "$(scan_repo_readme_state "$MIRROR_DIR")" == "generated" ]]; then
        echo "  Dashboard README: present (sync requires the mirror to be verified"
        echo "                    private; 'greens --privacy-migrate' scrubs it)"
      fi
    fi
    echo "  Mirror email: ${MIRROR_EMAIL:-not set}"
    echo "  GitHub user:  ${GITHUB_USERNAME:-not set}"
    echo "  Activity:     ${ACTIVITY_TYPES:-commits}"
    echo "  Since:        ${SINCE:-not set}"
    # Last sync
    log_dir="${LOG_DIR:-$HOME/.contrib-mirror/logs}"
    [[ -d "$log_dir" ]] || log_dir="$SCRIPT_DIR/logs"
    stamp_file="${SUCCESS_STAMP_FILE:-$log_dir/last-success-date}"
    if [[ -f "$stamp_file" ]]; then
      echo "  Last sync:    $(cat "$stamp_file")"
    else
      echo "  Last sync:    never"
    fi
    # Scheduler
    if launchctl list 2>/dev/null | grep -q "com.greens"; then
      echo "  Scheduler:    launchd (active)"
    elif crontab -l 2>/dev/null | grep -q "sync.sh"; then
      echo "  Scheduler:    cron"
    elif schtasks.exe /Query /TN "greens-daily-sync" 2>/dev/null | grep -qi "greens"; then
      echo "  Scheduler:    Windows Task Scheduler (active)"
    else
      echo "  Scheduler:    none (manual)"
    fi
    exit 0 ;;
  --reset)
    echo "greens — reset"
    echo ""
    confirm_reset() {
      printf "  %s [y/N]: " "$1" >&2
      read -r reply
      [[ "$reply" =~ ^[Yy] ]]
    }
    # 1. Scheduler
    if launchctl list 2>/dev/null | grep -q "com.greens"; then
      if confirm_reset "Remove launchd scheduler?"; then
        launchctl bootout "gui/$(id -u)/com.greens" 2>/dev/null || true
        rm -f "$HOME/Library/LaunchAgents/com.greens.plist"
        echo "  [ok] launchd agent removed"
      fi
    fi
    if crontab -l 2>/dev/null | grep -q "sync.sh"; then
      if confirm_reset "Remove cron entry?"; then
        crontab -l 2>/dev/null | grep -v "sync.sh" | crontab -
        echo "  [ok] cron entry removed"
      fi
    fi
    if schtasks.exe /Query /TN "greens-daily-sync" 2>/dev/null | grep -qi "greens"; then
      if confirm_reset "Remove Windows Task Scheduler entry?"; then
        MSYS_NO_PATHCONV=1 schtasks.exe /Delete /TN "greens-daily-sync" /F 2>/dev/null || true
        echo "  [ok] Windows scheduled task removed"
      fi
    fi
    # 2. Cache (new default location + legacy script-dir location)
    config_dir="$HOME/.contrib-mirror"
    for cache_dir in "$config_dir/cache" "$SCRIPT_DIR/.cache"; do
      if [[ -d "$cache_dir" ]]; then
        if confirm_reset "Remove cache dir ($cache_dir)?"; then
          rm -rf "$cache_dir"
          echo "  [ok] cache removed"
        fi
      fi
    done
    # 3. Mirror (before config removal — needs MIRROR_DIR from config)
    mirror="${MIRROR_DIR:-$config_dir/mirror}"
    if [[ -d "$mirror" ]]; then
      if confirm_reset "Remove mirror repo ($mirror)? This deletes all mirrored commits."; then
        rm -rf "$mirror"
        echo "  [ok] mirror removed"
      fi
    fi
    # 4. Config
    if [[ -f "$CONFIG_FILE" ]]; then
      if confirm_reset "Remove config ($CONFIG_FILE)?"; then
        rm -f "$CONFIG_FILE"
        echo "  [ok] config removed"
      fi
    fi
    # 5. Logs
    log_dir="${LOG_DIR:-$SCRIPT_DIR/logs}"
    config_log_dir="$config_dir/logs"
    for d in "$log_dir" "$config_log_dir"; do
      if [[ -d "$d" ]]; then
        if confirm_reset "Remove logs ($d)?"; then
          rm -rf "$d"
          echo "  [ok] logs removed"
        fi
      fi
    done
    # 6. Config dir if empty
    if [[ -d "$config_dir" ]] && [[ -z "$(ls -A "$config_dir" 2>/dev/null)" ]]; then
      rmdir "$config_dir" 2>/dev/null || true
    fi
    echo ""
    echo "  Done. Run 'greens' to set up again."
    exit 0 ;;
  -*)
    echo "Unknown option: $1" >&2
    echo "See: greens --help" >&2
    exit 1 ;;
esac

# Auto-run setup on first use
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "No config found. Starting setup wizard..."
  echo ""
  "$SCRIPT_DIR/setup.sh"
  # If setup failed or user exited without creating config, bail
  if [[ ! -f "$CONFIG_FILE" ]]; then
    exit 1
  fi
  # Reload config written by setup
  source "$CONFIG_FILE"
  echo ""
  echo "Starting first sync..."
  echo ""
fi

# ─────────────────────────────────────────────────────────────────────────────
# Configuration (override via environment or edit below)
# ─────────────────────────────────────────────────────────────────────────────

# Directory containing your private work repos (will scan for git repos here)
WORK_DIR="${WORK_DIR:-$HOME/work}"

# Where to cache bare clones (avoids touching your working repos).
# Default moved to ~/.contrib-mirror/cache in v1.8.2 — the old $SCRIPT_DIR
# default broke symlinked installs and dumped caches into /usr/local/bin.
# Migrate an existing script-dir cache once, so repos aren't re-cloned.
if [[ -z "${CACHE_DIR:-}" ]]; then
  CACHE_DIR="$HOME/.contrib-mirror/cache"
  if [[ -d "$SCRIPT_DIR/.cache" ]] && [[ ! -e "$CACHE_DIR" ]]; then
    mkdir -p "$(dirname "$CACHE_DIR")" 2>/dev/null || true
    mv "$SCRIPT_DIR/.cache" "$CACHE_DIR" 2>/dev/null || CACHE_DIR="$SCRIPT_DIR/.cache"
  fi
fi

# Your public mirror repo (create this on GitHub first)
MIRROR_DIR="${MIRROR_DIR:-$HOME/.contrib-mirror/mirror}"

# Only sync commits after this date
SINCE="${SINCE:-2024-01-01 00:00:00}"

# Your git emails (commits by these emails will be mirrored)
EMAILS="${EMAILS:-your-work-email@company.com,your-personal@gmail.com}"

# Remote URL prefix to match (e.g., "git@github.com:your-company/")
# Only repos with origin URLs starting with this prefix will be synced
REMOTE_PREFIX="${REMOTE_PREFIX:-git@github.com:your-company/}"

# GitHub organization name (extracted from REMOTE_PREFIX if not set)
GITHUB_ORG="${GITHUB_ORG:-}"

# GitHub username for API queries (for PRs, reviews, issues)
GITHUB_USERNAME="${GITHUB_USERNAME:-}"

# GitHub token for work account API access (optional)
# Option A: Set GITHUB_TOKEN with a PAT from your work account (https://github.com/settings/tokens, 'repo' scope)
# Option B: Login with both accounts via `gh auth login`, set GITHUB_USERNAME to your work account
# If neither is set, gh CLI uses whatever account is currently active
GITHUB_TOKEN="${GITHUB_TOKEN:-}"

# Types of activity to track (comma-separated: commits,prs,issues; "reviews"
# can be added back explicitly, but PR updatedAt timestamps are unstable and
# mint phantom squares, so it's no longer a default as of v1.8.2)
# Set to "commits" only to disable GitHub API integration
ACTIVITY_TYPES="${ACTIVITY_TYPES:-commits,prs,issues}"

# Personal GitHub email for mirror commits (must match a verified email on
# your GitHub account). REQUIRED — there is deliberately no fallback to git's
# global user.email: on a work machine that would push your work identity to
# the mirror.
MIRROR_EMAIL="${MIRROR_EMAIL:-}"

# Author/committer name for mirror commits. Keep it generic — never a
# personal or work name.
MIRROR_NAME="${MIRROR_NAME:-greens}"

# Copy raw git commit subjects to mirror (0=timestamps only, 1=subjects).
# WARNING: subjects from private repos are published to anyone who can read
# the mirror; merge subjects commonly expose org and branch names. PR/review/
# issue activity always gets a generic label, never the title.
COPY_MESSAGES="${COPY_MESSAGES:-0}"

# Log directory. Default moved to ~/.contrib-mirror/logs in v1.8.2 (same
# symlinked-install reason as CACHE_DIR). Migrate old script-dir logs once so
# the daily success stamp survives the upgrade.
if [[ -z "${LOG_DIR:-}" ]]; then
  LOG_DIR="$HOME/.contrib-mirror/logs"
  if [[ -d "$SCRIPT_DIR/logs" ]] && [[ ! -e "$LOG_DIR" ]]; then
    mkdir -p "$(dirname "$LOG_DIR")" 2>/dev/null || true
    mv "$SCRIPT_DIR/logs" "$LOG_DIR" 2>/dev/null || LOG_DIR="$SCRIPT_DIR/logs"
  fi
fi

# Success stamp file (prevents running multiple times per day)
SUCCESS_STAMP_FILE="${SUCCESS_STAMP_FILE:-$LOG_DIR/last-success-date}"

# ─────────────────────────────────────────────────────────────────────────────
# Mirror identity — REQUIRED before anything else runs
# ─────────────────────────────────────────────────────────────────────────────

MIRROR_EMAIL="${MIRROR_EMAIL//[[:space:]]/}"

# Interactive terminal: offer the one-question inline fix.
if [[ -z "$MIRROR_EMAIL" ]] && [[ -t 0 ]] && [[ -f "$CONFIG_FILE" ]]; then
  echo "Your mirror commits need a personal GitHub email to show as green squares."
  echo "This must match a verified email on your GitHub account."
  printf "  Personal GitHub email: " >&2
  read -r MIRROR_EMAIL
  MIRROR_EMAIL="${MIRROR_EMAIL//[[:space:]]/}"
  if [[ -n "$MIRROR_EMAIL" ]]; then
    config_upsert "MIRROR_EMAIL" "MIRROR_EMAIL=\"\${MIRROR_EMAIL:-$MIRROR_EMAIL}\""
    echo "  Saved to config."
    echo ""
  fi
fi

# Noninteractive (launchd/cron) or still empty: hard-fail. Never fall back to
# the global git identity — that silently publishes a work name/email.
if [[ -z "$MIRROR_EMAIL" ]]; then
  echo "ERROR: MIRROR_EMAIL is not set. Mirror commits need your personal" >&2
  echo "GitHub email or the squares are never counted. Run: greens --setup" >&2
  exit 2
fi

# ─────────────────────────────────────────────────────────────────────────────
# COPY_MESSAGES needs the persisted setup acknowledgement. A scheduled run
# must never publish subjects because a config was hand-edited; it fails with
# instructions instead of prompting.
# ─────────────────────────────────────────────────────────────────────────────

if [[ "$COPY_MESSAGES" == "1" ]] && [[ "${COPY_MESSAGES_ACK:-0}" != "1" ]]; then
  echo "ERROR: COPY_MESSAGES=1 requires the typed acknowledgement from 'greens --setup'." >&2
  echo "Copying commit subjects publishes them to whoever can read the mirror; merge" >&2
  echo "subjects commonly expose org and branch names. Re-run 'greens --setup' to" >&2
  echo "acknowledge this, or set COPY_MESSAGES=0 for timestamps-only." >&2
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Setup
# ─────────────────────────────────────────────────────────────────────────────

mkdir -p "$CACHE_DIR" "$LOG_DIR"

# Convert comma-separated emails to an array, trimming stray whitespace so
# "a@x.com, b@y.com" doesn't silently drop the second address.
EMAIL_ARRAY=()
IFS=',' read -ra _raw_emails <<< "$EMAILS"
for _e in ${_raw_emails[@]+"${_raw_emails[@]}"}; do
  _e="${_e#"${_e%%[![:space:]]*}"}"   # ltrim
  _e="${_e%"${_e##*[![:space:]]}"}"   # rtrim
  if [[ -n "$_e" ]]; then
    EMAIL_ARRAY+=("$_e")
  fi
done

# Lock to prevent concurrent runs
LOCK_DIR="/tmp/greens-sync.lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  existing_pid=""
  if [[ -f "$LOCK_DIR/pid" ]]; then
    existing_pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
  fi

  if [[ -n "$existing_pid" ]] && ps -p "$existing_pid" >/dev/null 2>&1; then
    echo "Another sync is already running (pid: $existing_pid). Exiting."
    exit 0
  fi

  echo "Stale lock detected. Removing and continuing."
  rm -rf "$LOCK_DIR"
  mkdir "$LOCK_DIR"
fi

echo "$$" > "$LOCK_DIR/pid"

timestamp() {
  date "+%Y-%m-%d %H:%M:%S %z"
}

log() {
  echo "[$(timestamp)] $*"
}

# ─────────────────────────────────────────────────────────────────────────────
# GitHub Activity Functions (PRs, Reviews, Issues)
# ─────────────────────────────────────────────────────────────────────────────

# Convert ISO 8601 timestamp to git format
# Input:  2024-01-15T10:30:45Z or 2024-01-15T10:30:45+05:30
# Output: 2024-01-15 10:30:45 +0000 or 2024-01-15 10:30:45 +0530
iso_to_git_format() {
  local iso_ts="$1"
  if [[ "$iso_ts" == *"Z" ]]; then
    # UTC timestamp
    echo "$iso_ts" | sed 's/T/ /; s/Z/ +0000/'
  else
    # Timestamp with offset like +05:30
    echo "$iso_ts" | sed 's/T/ /; s/\([+-][0-9][0-9]\):\([0-9][0-9]\)$/ \1\2/'
  fi
}

# Fetch GitHub activity timestamps (PRs, reviews, issues)
fetch_github_activity() {
  local since_date="$1"
  local org="$2"

  # Check if gh CLI is available
  if ! command -v gh &>/dev/null; then
    echo "[$(date "+%Y-%m-%d %H:%M:%S %z")] WARN: gh CLI not found, skipping GitHub activity fetch" >&2
    return
  fi

  # Auth: GITHUB_TOKEN takes priority, otherwise try account switching
  if [[ -n "$GITHUB_TOKEN" ]]; then
    export GITHUB_TOKEN
  elif [[ -n "$GITHUB_USERNAME" ]]; then
    local original_account
    original_account=$(gh auth status --active 2>&1 | grep 'Logged in' | sed 's/.*account //' | awk '{print $1}' || true)
    if [[ "$original_account" != "$GITHUB_USERNAME" ]]; then
      gh auth switch --user "$GITHUB_USERNAME" &>/dev/null || true
    fi
    trap 'if [[ -n "${original_account:-}" && "${original_account}" != "$GITHUB_USERNAME" ]]; then gh auth switch --user "$original_account" &>/dev/null || true; fi' RETURN
  fi

  # Check gh auth status
  if ! gh auth status &>/dev/null; then
    echo "[$(date "+%Y-%m-%d %H:%M:%S %z")] WARN: gh CLI not authenticated, skipping GitHub activity fetch" >&2
    return
  fi

  # PRs created
  if [[ "$ACTIVITY_TYPES" == *"prs"* ]]; then
    gh search prs --author="$GITHUB_USERNAME" --created=">=$since_date" \
      --owner="$org" --json createdAt --jq '.[].createdAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then iso_to_git_format "$ts"; fi
      done
  fi

  # PR reviews
  if [[ "$ACTIVITY_TYPES" == *"reviews"* ]]; then
    gh search prs --reviewed-by="$GITHUB_USERNAME" --updated=">=$since_date" \
      --owner="$org" --json updatedAt --jq '.[].updatedAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then iso_to_git_format "$ts"; fi
      done
  fi

  # Issues created
  if [[ "$ACTIVITY_TYPES" == *"issues"* ]]; then
    gh search issues --author="$GITHUB_USERNAME" --created=">=$since_date" \
      --owner="$org" --json createdAt --jq '.[].createdAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then iso_to_git_format "$ts"; fi
      done
  fi
}

# Fetch GitHub activity as timestamp<TAB>label pairs (COPY_MESSAGES=1 mode).
# v1.8.2: PR/review/issue TITLES are never copied — they exposed org-wide
# information and add nothing to the graph. Fixed generic labels only.
fetch_github_activity_with_messages() {
  local since_date="$1"
  local org="$2"

  if ! command -v gh &>/dev/null; then
    echo "[$(date "+%Y-%m-%d %H:%M:%S %z")] WARN: gh CLI not found, skipping GitHub activity fetch" >&2
    return
  fi

  if [[ -n "$GITHUB_TOKEN" ]]; then
    export GITHUB_TOKEN
  elif [[ -n "$GITHUB_USERNAME" ]]; then
    local original_account
    original_account=$(gh auth status --active 2>&1 | grep 'Logged in' | sed 's/.*account //' | awk '{print $1}' || true)
    if [[ "$original_account" != "$GITHUB_USERNAME" ]]; then
      gh auth switch --user "$GITHUB_USERNAME" &>/dev/null || true
    fi
    trap 'if [[ -n "${original_account:-}" && "${original_account}" != "$GITHUB_USERNAME" ]]; then gh auth switch --user "$original_account" &>/dev/null || true; fi' RETURN
  fi

  if ! gh auth status &>/dev/null; then
    echo "[$(date "+%Y-%m-%d %H:%M:%S %z")] WARN: gh CLI not authenticated, skipping GitHub activity fetch" >&2
    return
  fi

  if [[ "$ACTIVITY_TYPES" == *"prs"* ]]; then
    gh search prs --author="$GITHUB_USERNAME" --created=">=$since_date" \
      --owner="$org" --json createdAt --jq '.[].createdAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then printf '%s\tPR activity\n' "$(iso_to_git_format "$ts")"; fi
      done
  fi

  if [[ "$ACTIVITY_TYPES" == *"reviews"* ]]; then
    gh search prs --reviewed-by="$GITHUB_USERNAME" --updated=">=$since_date" \
      --owner="$org" --json updatedAt --jq '.[].updatedAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then printf '%s\tReview activity\n' "$(iso_to_git_format "$ts")"; fi
      done
  fi

  if [[ "$ACTIVITY_TYPES" == *"issues"* ]]; then
    gh search issues --author="$GITHUB_USERNAME" --created=">=$since_date" \
      --owner="$org" --json createdAt --jq '.[].createdAt' 2>/dev/null | \
      while read -r ts; do
        if [[ -n "$ts" ]]; then printf '%s\tIssue activity\n' "$(iso_to_git_format "$ts")"; fi
      done
  fi
}

tmp_pairs="$(mktemp)"
tmp_sorted="$(mktemp)"
cleanup() {
  rm -f "$tmp_pairs" "$tmp_sorted" /tmp/greens_*.txt 2>/dev/null || true
  rm -rf "$LOCK_DIR" 2>/dev/null || true
}
trap cleanup EXIT

# ─────────────────────────────────────────────────────────────────────────────
# Privacy gate: refuse to build on legacy (<= 1.8.1) generated-README history.
# Runs BEFORE the daily-stamp early exit so upgrade day can't silently no-op,
# and only after refreshing the mirror's remote refs — a stale local clone
# can't vouch for the remote. FORCE=1 and --resync do not bypass this.
# ─────────────────────────────────────────────────────────────────────────────

if [[ -d "${MIRROR_DIR}/.git" ]]; then
  if [[ -f "$MIRROR_DIR/.git/config" ]] && [[ ! -O "$MIRROR_DIR/.git/config" ]]; then
    echo "ERROR: $MIRROR_DIR/.git/config is not owned by the current user. Refusing." >&2
    exit 1
  fi
  if git -C "$MIRROR_DIR" remote get-url origin >/dev/null 2>&1; then
    # ALL advertised refs (notes/custom included) — legacy history reachable
    # only through a stray ref must still trip the gate.
    if ! git -C "$MIRROR_DIR" fetch --prune origin "+refs/heads/*:refs/remotes/origin/*" "+refs/*:refs/greens-remote-scan/*" --quiet 2>/dev/null; then
      # Local evidence of dashboard history + no proof of privacy refuses
      # immediately; a CLEAN local result is likewise not authoritative while
      # the remote is unreachable.
      if [[ "$(scan_repo_readme_state "$MIRROR_DIR")" == "generated" ]] && \
         [[ "$(mirror_visibility)" != "private" ]]; then
        legacy_refuse
      fi
      log "ERROR: couldn't refresh the mirror from origin for the privacy check."
      log "A stale local clone can't prove the remote is clean — refusing to sync."
      log "Fix access to the mirror remote and re-run."
      exit 1
    fi
  fi
  legacy_state="$(scan_repo_readme_state "$MIRROR_DIR")"
  if [[ "$legacy_state" == "generated" ]]; then
    # The dashboard README (work repo names) is allowed to exist ONLY where
    # nobody but the owner can read it: a positively verified PRIVATE GitHub
    # mirror. Public or unverifiable (gh missing/unauthenticated, non-GitHub
    # remote) trips the refusal.
    if [[ "$(mirror_visibility)" == "private" ]]; then
      log "Mirror is verified private — dashboard README history is OK here."
    else
      legacy_refuse
    fi
  elif [[ "$legacy_state" == "foreign" ]]; then
    log "NOTE: the mirror has a README greens didn't generate; it is left alone."
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# Skip if already synced today (set FORCE=1 to override)
# ─────────────────────────────────────────────────────────────────────────────

today="$(date '+%Y-%m-%d')"
if [[ "${FORCE:-0}" != "1" ]] && [[ -f "$SUCCESS_STAMP_FILE" ]]; then
  last_success_date="$(cat "$SUCCESS_STAMP_FILE" 2>/dev/null || true)"
  if [[ "$last_success_date" == "$today" ]]; then
    log "Already synced today ($today). Set FORCE=1 to run anyway."
    exit 0
  fi
fi

log "Starting contribution mirror sync"
log ""
log "Step 1/5: Finding work repos in $WORK_DIR"
log "  (Looking for git repos that match your org: $REMOTE_PREFIX)"

# ─────────────────────────────────────────────────────────────────────────────
# Discover repos
# ─────────────────────────────────────────────────────────────────────────────

find "$WORK_DIR" -maxdepth 2 -name .git -print 2>/dev/null | while read -r gitpath; do
  repodir="$(dirname "$gitpath")"

  # Skip cache directory
  case "$repodir" in
    "$CACHE_DIR"/*) continue ;;
  esac

  url="$(git -C "$repodir" remote get-url origin 2>/dev/null || true)"
  if [[ -z "$url" ]]; then
    continue
  fi

  # Only process repos matching the org. Accept any clone form (SSH/HTTPS/git://)
  # and normalize to REMOTE_PREFIX so downstream cache/filter logic stays consistent.
  prefix_trimmed="${REMOTE_PREFIX%/}"
  if [[ "$prefix_trimmed" == *"://"* ]]; then
    org_from_prefix="${prefix_trimmed##*/}"   # https://host/Org -> Org
  else
    org_from_prefix="${prefix_trimmed##*:}"   # git@host:Org -> Org
  fi
  if [[ -z "$org_from_prefix" ]]; then
    case "$url" in
      "$REMOTE_PREFIX"*) ;;
      *) continue ;;
    esac
    remote_repo="$(basename "$url")"
    printf "%s %s\n" "$remote_repo" "$url" >> "$tmp_pairs"
    continue
  fi
  normalized=""
  case "$url" in
    "$REMOTE_PREFIX"*)
      normalized="$url"
      ;;
    *"/$org_from_prefix/"*|*":$org_from_prefix/"*)
      repo_path="${url##*$org_from_prefix/}"
      repo_path="${repo_path%.git}"
      if [[ -n "$repo_path" ]]; then
        normalized="${REMOTE_PREFIX}${repo_path}.git"
        [[ "$url" != "$normalized" ]] && log "  WARN: $repodir uses $url; normalizing to $normalized"
      fi
      ;;
  esac
  [[ -z "$normalized" ]] && continue
  url="$normalized"

  remote_repo="$(basename "$url")"
  printf "%s %s\n" "$remote_repo" "$url" >> "$tmp_pairs"
done

if [[ ! -s "$tmp_pairs" ]]; then
  log "No matching repos found under $WORK_DIR (prefix: $REMOTE_PREFIX)"
  exit 1
fi

LC_ALL=C sort -u "$tmp_pairs" > "$tmp_sorted"

# ─────────────────────────────────────────────────────────────────────────────
# Fetch into bare caches (safe for local WIP)
# ─────────────────────────────────────────────────────────────────────────────

# Never block on auth/host-key prompts and drop stalled SSH connections fast.
# Without ServerAliveInterval a midnight launchd/cron run can hang for hours
# when WiFi drops mid-transfer — ssh stays alive with no progress.
# Honor pre-set values so users can tune via their environment.
: "${GIT_TERMINAL_PROMPT:=0}"
: "${GIT_SSH_COMMAND:=ssh -o BatchMode=yes -o ServerAliveInterval=10 -o ServerAliveCountMax=3 -o ConnectTimeout=30}"
export GIT_TERMINAL_PROMPT GIT_SSH_COMMAND

# Per-fetch hard timeout so one stuck repo can't wedge the whole sync.
# Prefer GNU coreutils, then macOS-native timeout, else a Bash-native fallback
# that kills the whole process group.
GREENS_FETCH_TIMEOUT="${GREENS_FETCH_TIMEOUT:-120}"
if command -v gtimeout >/dev/null 2>&1; then
  TIMEOUT_CMD=(gtimeout --kill-after=10 "$GREENS_FETCH_TIMEOUT")
elif command -v timeout >/dev/null 2>&1; then
  TIMEOUT_CMD=(timeout --kill-after=10 "$GREENS_FETCH_TIMEOUT")
elif command -v perl >/dev/null 2>&1; then
  # perl setpgrp makes the exec'd command a process group leader, so
  # kill -TERM -$pid terminates git AND its ssh child. If setpgrp is a
  # no-op on this platform, the negative-pid kill falls back to the
  # positive-pid form so at least git itself gets terminated.
  run_with_timeout() {
    local seconds="$1"; shift
    perl -e 'setpgrp 0,0; exec @ARGV or die "exec failed: $!"' "$@" &
    local pid=$!
    (
      sleep "$seconds"
      kill -TERM -"$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null
      sleep 10
      kill -KILL -"$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null
    ) &
    local watcher=$!
    wait "$pid" 2>/dev/null
    local rc=$?
    kill "$watcher" 2>/dev/null
    wait "$watcher" 2>/dev/null
    return "$rc"
  }
  TIMEOUT_CMD=(run_with_timeout "$GREENS_FETCH_TIMEOUT")
else
  log "WARN: no timeout or perl available; fetches won't be bounded."
  TIMEOUT_CMD=()
fi

repo_total="$(wc -l < "$tmp_sorted" | tr -d " ")"
log ""
log "Step 2/5: Caching $repo_total repos (read-only copies — your code stays untouched)"

failures=0
fetched_ok=0
while read -r remote_repo url; do
  [[ -z "$remote_repo" ]] && continue
  bare="$CACHE_DIR/$remote_repo"

  if [[ ! -d "$bare" ]]; then
    log "Cloning $remote_repo"
    # ${arr[@]+...} guards the empty-array case — bash 3.2 + set -u aborts on
    # plain "${arr[@]}" when the array has no elements.
    if ! err="$(${TIMEOUT_CMD[@]+"${TIMEOUT_CMD[@]}"} git clone --bare --filter=blob:none --no-tags "$url" "$bare" 2>&1)"; then
      log "WARN: clone failed for $remote_repo: $(echo "$err" | tail -n 3 | tr '\n' ' ')"
      failures=$((failures + 1))
      rm -rf "$bare" >/dev/null 2>&1 || true
      continue
    fi
  fi

  git --git-dir="$bare" remote set-url origin "$url" >/dev/null 2>&1 || true

  if ! git --git-dir="$bare" config --get-all remote.origin.fetch >/dev/null 2>&1; then
    git --git-dir="$bare" config remote.origin.fetch "+refs/heads/*:refs/heads/*"
  fi

  log "Fetching $remote_repo"
  if ! err="$(${TIMEOUT_CMD[@]+"${TIMEOUT_CMD[@]}"} git --git-dir="$bare" fetch --prune --no-tags --filter=blob:none origin "+refs/heads/*:refs/heads/*" 2>&1)"; then
    log "WARN: fetch failed for $remote_repo: $(echo "$err" | tail -n 3 | tr '\n' ' ')"
    failures=$((failures + 1))
    continue
  fi
  fetched_ok=$((fetched_ok + 1))
done < "$tmp_sorted"

if [[ "$failures" -gt 0 ]]; then
  log "WARN: $failures repos failed to fetch"
fi

if [[ "$fetched_ok" -eq 0 ]]; then
  log "ERROR: all fetches failed; not proceeding with stale data."
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# Collect unique timestamps
# ─────────────────────────────────────────────────────────────────────────────

tmp_all_data="/tmp/greens_all.txt"
tmp_origin_ts="/tmp/greens_origin_ts.txt"
tmp_mirror_ts="/tmp/greens_mirror_ts.txt"
tmp_missing_ts="/tmp/greens_missing_ts.txt"
tmp_missing_data="/tmp/greens_missing_data.txt"

> "$tmp_all_data"

log ""
log "Step 3/5: Scanning commits across all branches (emails: $EMAILS)"
log "  (Checks every branch — feature, hotfix, etc. No double-counting after merge)"

# Collect git commits (with or without messages based on COPY_MESSAGES)
for bare in "$CACHE_DIR"/*.git; do
  [[ -d "$bare" ]] || continue

  origin_url="$(git --git-dir="$bare" remote get-url origin 2>/dev/null || true)"
  case "$origin_url" in
    "$REMOTE_PREFIX"*) ;;
    *) continue ;;
  esac

  # --fixed-strings: the email is matched literally, not as a regex ("a@x.com"
  # as a regex also matches "a@xX.com" — a colleague's activity could leak in).
  # --regexp-ignore-case: git emails are case-insensitive in practice.
  for email in ${EMAIL_ARRAY[@]+"${EMAIL_ARRAY[@]}"}; do
    if [[ "$COPY_MESSAGES" == "1" ]]; then
      git --git-dir="$bare" log --all --since="$SINCE" --fixed-strings --regexp-ignore-case --author="<$email>" --format="%ai	%s" 2>/dev/null || true
    else
      git --git-dir="$bare" log --all --since="$SINCE" --fixed-strings --regexp-ignore-case --author="<$email>" --format="%ai" 2>/dev/null || true
    fi
  done
done >> "$tmp_all_data"

# Fetch GitHub activity (PRs, reviews, issues)
if [[ "$ACTIVITY_TYPES" == *"reviews"* ]]; then
  log "NOTE: 'reviews' tracks PR updatedAt (not review time) and mints unstable squares; it's no longer a default. Remove it from ACTIVITY_TYPES to silence this."
fi
if [[ "$ACTIVITY_TYPES" != "commits" ]] && [[ -n "$GITHUB_USERNAME" ]]; then
  since_date="${SINCE%% *}"  # Extract date part only (YYYY-MM-DD)
  if [[ -z "$GITHUB_ORG" ]]; then
    GITHUB_ORG="$(echo "$REMOTE_PREFIX" | sed 's|.*[:/]\([^/]*\)/$|\1|')"
  fi
  log "Fetching GitHub activity (PRs, reviews, issues) since $since_date..."

  if [[ "$COPY_MESSAGES" == "1" ]]; then
    # Fetch with titles (timestamp<TAB>message format)
    fetch_github_activity_with_messages "$since_date" "$GITHUB_ORG" >> "$tmp_all_data"
  else
    # Fetch timestamps only
    fetch_github_activity "$since_date" "$GITHUB_ORG" >> "$tmp_all_data"
  fi

  total_count="$(wc -l < "$tmp_all_data" | tr -d " ")"
  log "Total entries (commits + GitHub activity): $total_count"
fi

# Deduplicate and extract timestamps for comparison
if [[ "$COPY_MESSAGES" == "1" ]]; then
  LC_ALL=C sort -t$'\t' -k1,1 -u "$tmp_all_data" > "$tmp_all_data.sorted"
  mv "$tmp_all_data.sorted" "$tmp_all_data"
  cut -f1 "$tmp_all_data" | LC_ALL=C sort -u > "$tmp_origin_ts"
else
  LC_ALL=C sort -u "$tmp_all_data" > "$tmp_origin_ts"
fi

{ git -C "$MIRROR_DIR" log --format="%ai" 2>/dev/null || true; } | LC_ALL=C sort -u > "$tmp_mirror_ts"
comm -23 "$tmp_origin_ts" "$tmp_mirror_ts" > "$tmp_missing_ts"

# Build missing data file (with messages if enabled)
if [[ "$COPY_MESSAGES" == "1" ]]; then
  > "$tmp_missing_data"
  while IFS= read -r ts; do
    [[ -z "$ts" ]] && continue
    msg="$(grep "^${ts}	" "$tmp_all_data" 2>/dev/null | head -1 | cut -f2-)"
    [[ -z "$msg" ]] && msg="sync"
    printf '%s\t%s\n' "$ts" "$msg" >> "$tmp_missing_data"
  done < "$tmp_missing_ts"
fi

origin_count="$(wc -l < "$tmp_origin_ts" | tr -d " ")"
mirror_count="$(wc -l < "$tmp_mirror_ts" | tr -d " ")"
missing_count="$(wc -l < "$tmp_missing_ts" | tr -d " ")"

log "Origin timestamps: $origin_count"
log "Mirror timestamps: $mirror_count"
log "Missing (to sync): $missing_count"

# ─────────────────────────────────────────────────────────────────────────────
# Add missing commits to mirror
# ─────────────────────────────────────────────────────────────────────────────

log ""
log "Step 4/5: Creating mirror commits (these show up as green squares on GitHub)"

# Every synthetic commit gets the mirror identity pinned via BOTH environment
# and -c overrides. MIRROR_EMAIL is guaranteed non-empty (hard-fail above);
# never let the machine's git identity leak into the mirror.

if [[ "$missing_count" -gt 0 ]]; then
  log "Adding $missing_count new commits to mirror..."
  cd "$MIRROR_DIR"

  if [[ "$COPY_MESSAGES" == "1" ]]; then
    while IFS=$'\t' read -r ts msg; do
      [[ -z "$ts" ]] && continue
      [[ -z "$msg" ]] && msg="sync"
      GIT_AUTHOR_DATE="$ts" GIT_COMMITTER_DATE="$ts" \
      GIT_AUTHOR_NAME="$MIRROR_NAME" GIT_AUTHOR_EMAIL="$MIRROR_EMAIL" \
      GIT_COMMITTER_NAME="$MIRROR_NAME" GIT_COMMITTER_EMAIL="$MIRROR_EMAIL" \
        git -c user.name="$MIRROR_NAME" -c user.email="$MIRROR_EMAIL" \
          commit --allow-empty -m "$msg" --quiet
    done < "$tmp_missing_data"
  else
    while IFS= read -r ts; do
      [[ -z "$ts" ]] && continue
      GIT_AUTHOR_DATE="$ts" GIT_COMMITTER_DATE="$ts" \
      GIT_AUTHOR_NAME="$MIRROR_NAME" GIT_AUTHOR_EMAIL="$MIRROR_EMAIL" \
      GIT_COMMITTER_NAME="$MIRROR_NAME" GIT_COMMITTER_EMAIL="$MIRROR_EMAIL" \
        git -c user.name="$MIRROR_NAME" -c user.email="$MIRROR_EMAIL" \
          commit --allow-empty -m "sync" --quiet
    done < "$tmp_missing_ts"
  fi
  log "Mirror commits added."
else
  log "Mirror already up to date."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Dashboard README — PRIVATE mirrors only
#
# The dashboard lists work repo NAMES with per-repo commit counts. That is a
# feature when only the owner can read it, and a leak everywhere else. It is
# written ONLY when the mirror is positively verified PRIVATE on GitHub
# (cached gh check, one API call per run). Public or unverifiable mirrors —
# including non-GitHub remotes — never get the repo-names table.
# Same format as v1.8.1, so the ownership signature detection recognizes its
# own output; the visibility check is what keeps a fresh dashboard from
# tripping the privacy gate on the next run.
# ─────────────────────────────────────────────────────────────────────────────

if [[ "$(mirror_visibility)" == "private" ]]; then
  log ""
  log "Updating dashboard README (mirror is verified private)"

  STATUS_FILE="$MIRROR_DIR/README.md"
  final_mirror_count="$(git -C "$MIRROR_DIR" log --format="%ai" 2>/dev/null | LC_ALL=C sort -u | wc -l | tr -d " ")"

  # Collect per-repo stats
  tmp_repo_stats="$(mktemp)"
  tmp_dates="$(mktemp)"
  for bare in "$CACHE_DIR"/*.git; do
    [[ -d "$bare" ]] || continue
    repo_name="$(basename "$bare" .git)"

    origin_url="$(git --git-dir="$bare" remote get-url origin 2>/dev/null || true)"
    case "$origin_url" in
      "$REMOTE_PREFIX"*) ;;
      *) continue ;;
    esac

    repo_commits=0
    for email in ${EMAIL_ARRAY[@]+"${EMAIL_ARRAY[@]}"}; do
      count="$(git --git-dir="$bare" log --all --since="$SINCE" --fixed-strings --regexp-ignore-case --author="<$email>" --format="%H" 2>/dev/null | wc -l | tr -d " ")"
      repo_commits=$((repo_commits + count))
      git --git-dir="$bare" log --all --since="$SINCE" --fixed-strings --regexp-ignore-case --author="<$email>" --format="%ad" --date=short 2>/dev/null >> "$tmp_dates" || true
    done

    if [[ "$repo_commits" -gt 0 ]]; then
      printf "%d|%s\n" "$repo_commits" "$repo_name" >> "$tmp_repo_stats"
    fi
  done

  sorted_repos="$(sort -t'|' -k1 -nr "$tmp_repo_stats")"
  total_commits="$(echo "$sorted_repos" | awk -F'|' '{sum+=$1} END {print sum}')"
  total_commits="${total_commits:-0}"

  # Build repo breakdown
  repo_breakdown=""
  while IFS='|' read -r count name; do
    [[ -z "$count" ]] && continue
    if [[ "$total_commits" -gt 0 ]]; then
      percentage=$((count * 100 / total_commits))
    else
      percentage=0
    fi
    bar_length=$((percentage / 5))
    bar=""
    for ((i=0; i<bar_length; i++)); do bar+="█"; done
    for ((i=bar_length; i<20; i++)); do bar+="░"; done
    repo_breakdown+="| \`$name\` | $count | $bar $percentage% |
"
  done <<< "$sorted_repos"

  total_active_days="$(LC_ALL=C sort -u "$tmp_dates" | wc -l | tr -d " ")"
  repo_count="$(echo "$sorted_repos" | grep -c '|' || echo 0)"

  mirror_mode="timestamps only"
  [[ "$COPY_MESSAGES" == "1" ]] && mirror_mode="timestamps + messages"

  cat > "$STATUS_FILE" << EOF
# Work Contributions Mirror

This repository mirrors commit ${mirror_mode} from private work repositories to maintain GitHub contribution visibility.

---

## Overview

| Metric | Value |
|:-------|------:|
| Total Commits | **$total_commits** |
| Active Days | **$total_active_days** |
| Repos Tracked | **$repo_count** |
| Since | $SINCE |

---

## Repository Breakdown

| Repository | Commits | Distribution |
|:-----------|--------:|:-------------|
$repo_breakdown
---

## Sync Info

| | |
|:--|:--|
| Last Sync | \`$(timestamp)\` |
| Mirror Commits | $final_mirror_count |
| Added This Run | $missing_count |
| Status | $(if [[ "$missing_count" -gt 0 ]]; then echo "✓ Synced"; else echo "✓ Up to date"; fi) |

---

<sub>Generated by [greens](https://github.com/yuvrajangadsingh/greens)</sub>
EOF

  rm -f "$tmp_repo_stats" "$tmp_dates" 2>/dev/null || true

  # Commit the dashboard only when this run actually synced something.
  # The status commit uses a NEUTRAL non-account identity so it never paints
  # a contribution square (author date would be "now" — a phantom day).
  cd "$MIRROR_DIR"
  git add README.md
  if ! git diff --cached --quiet && [[ "$missing_count" -gt 0 ]]; then
    GIT_AUTHOR_NAME="greens-status" GIT_AUTHOR_EMAIL="status@greens.local" \
    GIT_COMMITTER_NAME="greens-status" GIT_COMMITTER_EMAIL="status@greens.local" \
      git -c user.name="greens-status" -c user.email="status@greens.local" \
        commit -m "Update sync status" --quiet
    log "Dashboard README updated."
  fi
else
  log ""
  log "Mirror is not verified private ($(mirror_visibility)) — the repo-names dashboard README is not written."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Push
# ─────────────────────────────────────────────────────────────────────────────

log ""
log "Step 5/5: Pushing to GitHub (making your contribution graph green)"

if ! git -C "$MIRROR_DIR" rev-parse --verify --quiet HEAD >/dev/null 2>&1; then
  # Brand-new mirror with zero activity found: nothing to push yet.
  log "Mirror has no commits yet (no matching activity found). Nothing to push."
  if [[ "${GREENS_PUSH_FORCE:-0}" == "1" ]]; then
    log "WARN: remote history was NOT overwritten — there are no local commits to push."
  fi
else
  do_push() {
    if [[ "${GREENS_PUSH_FORCE:-0}" == "1" ]]; then
      git -C "$MIRROR_DIR" push --force origin HEAD 2>&1
    else
      git -C "$MIRROR_DIR" push origin HEAD 2>&1
    fi
  }
  push_output=""
  if push_output="$(do_push)"; then
    log "Mirror pushed."
  else
    log "ERROR: Push to mirror repo failed."
    log "$push_output"
    log ""
    log "Your commits were created locally but won't show on GitHub until push works."
    log "Fix: re-run 'greens --setup' to reconfigure push access,"
    log "  or manually: git -C \"$MIRROR_DIR\" remote set-url origin https://<token>@github.com/<user>/<repo>.git"
    # No success stamp on failure — the next scheduled run must retry instead
    # of silently skipping the day.
    exit 1
  fi
  log "Mirror tip: $(git -C "$MIRROR_DIR" log -1 --format='%h %ai %s' 2>/dev/null || true)"
fi

# Stamp success atomically, and only after the push (or up-to-date) succeeded.
echo "$today" > "$SUCCESS_STAMP_FILE.tmp.$$"
mv "$SUCCESS_STAMP_FILE.tmp.$$" "$SUCCESS_STAMP_FILE"
log "Done."
